// This file was autogenerated by node_modules/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/jsonrpc/angulartransport.js', ['jsonrpc.AngularTransport'], ['jsonrpc.Transport']);
goog.addDependency('../../../../src/jsonrpc/dispatcher.js', ['jsonrpc.Dispatcher'], ['goog.Promise', 'goog.log', 'jsonrpc.Error']);
goog.addDependency('../../../../src/jsonrpc/error.js', ['jsonrpc.Error', 'jsonrpc.ErrorCode'], []);
goog.addDependency('../../../../src/jsonrpc/expressjs.js', ['jsonrpc.expressjs'], []);
goog.addDependency('../../../../src/jsonrpc/jquerytransport.js', ['jsonrpc.JqueryTransport'], ['goog.Promise', 'jsonrpc.Error', 'jsonrpc.Transport']);
goog.addDependency('../../../../src/jsonrpc/jsonrpc.js', ['jsonrpc'], ['goog.Promise', 'jsonrpc.Error']);
goog.addDependency('../../../../src/jsonrpc/nodehttptransport.js', ['jsonrpc.NodeHttpTransport'], ['goog.Promise', 'jsonrpc.Error', 'jsonrpc.Transport']);
goog.addDependency('../../../../src/jsonrpc/transport.js', ['jsonrpc.Transport'], []);
goog.addDependency('../../../../src/jsonrpc/xdmhandler.js', ['jsonrpc.XdmHandler'], []);
goog.addDependency('../../../../src/jsonrpc/xdmtransport.js', ['jsonrpc.XdmTransport'], ['goog.log', 'jsonrpc.Transport']);
goog.addDependency('../../../../src/jsonrpc/xhriotransport.js', ['jsonrpc.JsonRpcIo', 'jsonrpc.XhrIoTransport'], ['goog.Uri', 'goog.events.EventTarget', 'goog.json', 'goog.net.EventType', 'goog.net.XhrIo', 'jsonrpc.Error', 'jsonrpc.Transport']);
