// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/jsonrpc-ng.js', ['jsonrpc-ng'], ['jsonrpc', 'jsonrpc.AngularTransport', 'jsonrpc.Client'], false);
goog.addDependency('../../../../src/jsonrpc/client.js', ['jsonrpc.Client'], ['goog.Promise', 'jsonrpc'], false);
goog.addDependency('../../../../src/jsonrpc/dispatcher.js', ['jsonrpc.Dispatcher'], ['goog.Promise', 'goog.log', 'jsonrpc.Error'], false);
goog.addDependency('../../../../src/jsonrpc/error.js', ['jsonrpc.Error', 'jsonrpc.ErrorCode'], [], false);
goog.addDependency('../../../../src/jsonrpc/jsonrpc.js', ['jsonrpc'], ['goog.Promise', 'jsonrpc.Error'], false);
goog.addDependency('../../../../src/jsonrpc/serve/express.js', ['jsonrpc.serve.express'], [], false);
goog.addDependency('../../../../src/jsonrpc/transport.js', ['jsonrpc.Transport'], [], false);
goog.addDependency('../../../../src/jsonrpc/transport/angularjstransport.js', ['jsonrpc.AngularJSTransport'], ['jsonrpc.Transport'], false);
goog.addDependency('../../../../src/jsonrpc/transport/angulartransport.js', ['jsonrpc.AngularTransport'], ['jsonrpc.Transport'], false);
goog.addDependency('../../../../src/jsonrpc/transport/httpendpoint.js', ['jsonrpc.HttpEndpoint'], [], false);
goog.addDependency('../../../../src/jsonrpc/transport/jquerytransport.js', ['jsonrpc.JqueryTransport'], ['goog.Promise', 'jsonrpc.Error', 'jsonrpc.Transport'], false);
goog.addDependency('../../../../src/jsonrpc/transport/nodehttptransport.js', ['jsonrpc.NodeHttpTransport'], ['goog.Promise', 'jsonrpc.Error', 'jsonrpc.Transport'], false);
goog.addDependency('../../../../src/jsonrpc/transport/xdmhandler.js', ['jsonrpc.XdmHandler'], [], false);
goog.addDependency('../../../../src/jsonrpc/transport/xdmtransport.js', ['jsonrpc.XdmTransport'], ['goog.log', 'jsonrpc.Transport'], false);
goog.addDependency('../../../../src/jsonrpc/transport/xhriotransport.js', ['jsonrpc.JsonRpcIo', 'jsonrpc.XhrIoTransport'], ['goog.Uri', 'goog.events.EventTarget', 'goog.json', 'goog.net.EventType', 'goog.net.XhrIo', 'jsonrpc.Error', 'jsonrpc.Transport'], false);
